FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./Web/Web.csproj"
RUN dotnet build "./Web/Web.csproj" -c Release -o /app/build

FROM build AS publish
RUN apt-get update
RUN apt-get install -y python3
RUN dotnet workload install wasm-tools
RUN dotnet publish "./Web/Web.csproj" -c Release -o /app/publish

FROM nginx:alpine AS final
WORKDIR /usr/share/nginx/html
COPY --from=publish /app/publish/wwwroot .
COPY "./Web/nginx.conf" /etc/nginx/nginx.conf
