FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .
RUN dotnet restore "./Worker/Worker.csproj"
RUN dotnet publish "./Worker/Worker.csproj" -c release -o /app --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app ./

EXPOSE 5002

ENTRYPOINT [ "dotnet", "Worker.dll" ]
